[package]
name = "patina_pi"
resolver = "2"
version.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
description = "Platform Initialization (PI) Specification definitions and support code in Rust."

[dependencies]
indoc = {workspace = true}
num-traits = {workspace = true}
r-efi = {workspace = true}
uuid = {workspace = true}
serde = { workspace = true, default-features = false, optional = true, features = [
  "alloc",
  "derive",
] }
serde_json = { workspace = true, default-features = false, optional = true, features = ["alloc"] }

[dev-dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
brotli-decompressor = { workspace = true, default-features = false}
alloc-no-stdlib = {workspace = true}

[features]
nightly = []
std = []
serde = ["dep:serde", "dep:serde_json"]
